project:
  type: website
  output-dir: docs

website:
  title: "WALKER DATA"
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/walkerke
      - icon: twitter
        href: https://twitter.com/kyle_e_walker
format:
  html:
    theme: cosmo
    max-width: 600px
    css: styles.css



