---
title: "About"
about:
  template: marquee
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/kyle_e_walker
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/walkerke
    - icon: github
      text: Github
      href: https://github.com/walkerke

---

__WALKER DATA__ is a consultancy helping clients solve a wide range of data science problems.  We specialize in the following areas: 

* Spatial data science and Geographic Information Systems (GIS)
* Demographics and location intelligence
* Predictive analytics and machine learning
* Data visualization and dashboard development with tools like Shiny, Mapbox, and Tableau
* Coaching and training for the R and Python programming languages.  

```{=html}
<!-- Calendly link widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/kylewalker/intro-call'});return false;">Book a discovery call today!</a>
<!-- Calendly link widget end -->
```


<br/>

WALKER DATA is led by its principal, Kyle Walker, Ph.D.  Kyle is an internationally-recognized researcher, consultant, and software developer in the field of spatial data science, and was the 2022 recipient of the Spatial Data Scientist of the Year award from the software company CARTO.  He is the author of the book Analyzing US Census Data: Methods, Maps, and Models in R, and has published several popular software packages for spatial data science in R and Python that have been collectively downloaded over 1 million times. 

Kyle also serves as Director of Research for the Linnaean Company, a data science and strategy firm helping companies with business and location intelligence solutions.  [Learn more about the Linnaean Company here](https://www.linnaean.co/).


<style>
 a {
   color: #1a730f; 
 }

 .btn-outline-dark:hover {
     color: #fff;
     background-color: #1a730f;
     border-color: #343a40;
 }
</style>
