---
title: "Workshops"
---

Register today for these upcoming online workshops: 

Workshop 1: [__Analyzing the New 2020 Decennial Census Data__](https://www.eventbrite.com/e/access-and-analyze-the-new-2020-decennial-census-data-tickets-632022023887)

June 14, 2023, 11:00am-1:30pm Central Time (US)

In this workshop, you'll learn how to analyze the 2020 Decennial Census's Demographic and Housing Characteristics file using R and the tidycensus R package.  Topics covered will include brand-new functionality in tidycensus to acquire and process data from the 2020 DHC file to help you analyze the data right away.  You'll gain experience with the tidyverse ecosystem of tools to reveal insights in the new data, and you'll learn how to create stunning data visualizations to communicate those insights.  


```{=html}
<div class="center">
    <a href="https://www.eventbrite.com/e/access-and-analyze-the-new-2020-decennial-census-data-tickets-632022023887"><button class="custom-button">Register here</button></a>
</div>
<br/>

```

Workshop 2: [__Mapping and Spatial Analysis with the 2020 Decennial Census__](https://www.eventbrite.com/e/mapping-and-spatial-analysis-with-the-2020-decennial-census-tickets-641300375687)

June 21, 2023, 11:00am-1:30pm Central Time (US)

Maps are powerful tools for communicating insights in the 2020 DHC data.  In this workshop, you'll learn how to use R and tidycensus to get spatial Census data seamlessly, and visualize the new data with a range of cartographic tools.  You'll also learn all about Census geography and how to perform powerful spatial analyses with 2020 Census data.  

```{=html}
<div class="center">
    <a href="https://www.eventbrite.com/e/mapping-and-spatial-analysis-with-the-2020-decennial-census-tickets-641300375687"><button class="custom-button">Register here</button></a>
</div>
<br/>
```


Workshop participants get the following materials: 
* Unlimited access to the workshop video
* A custom tutorial on working with Census data not posted anywhere else
* 30 minutes live Q&A with Kyle Walker, the developer of the tidycensus R package

For updates on these workshops and more data analysis content, subscribe to the Walker Data mailing list:

```{=html}
<!-- Begin MailChimp Signup Form -->
<link href="https://cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://github.us15.list-manage.com/subscribe/post?u=1829a68a5eda3d301119fdcd6&amp;id=c4a53d2961" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div id="mc_embed_signup_scroll">

<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_1829a68a5eda3d301119fdcd6_c4a53d2961" tabindex="-1" value=""></div>
<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</div>
</form>
</div>


<!--End mc_embed_signup-->
```



__WALKER DATA__ also offers custom data science workshops that can be tailored to the needs of your organization.  Please reach out to <kyle@walker-data.com> to discuss!



<style>
 a {
   color: #1a730f; 
 }

 .btn-outline-dark:hover {
     color: #fff;
     background-color: #1a730f;
     border-color: #343a40;
 }
</style>
